//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: netProto.proto
namespace CustomProtocol
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerConnectReq")]
  public partial class PlayerConnectReq : global::ProtoBuf.IExtensible
  {
    public PlayerConnectReq() {}
    
    private string _playName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playName
    {
      get { return _playName; }
      set { _playName = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerConnectRsp")]
  public partial class PlayerConnectRsp : global::ProtoBuf.IExtensible
  {
    public PlayerConnectRsp() {}
    
    private string _playId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playId
    {
      get { return _playId; }
      set { _playId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}